name: Build Garmin App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: "11"

    - name: Install Garmin Connect IQ SDK
      run: |
        wget https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-lin-3.1.9-2020-06-24-1cc9d3a70.zip
        unzip connectiq-sdk-lin-3.1.9-2020-06-24-1cc9d3a70.zip -d ~/connectiq-sdk
        echo "CONNECTIQ_HOME=~/connectiq-sdk" >> $GITHUB_ENV

    - name: Generate a Private Key
      run: |
        openssl genpkey -algorithm RSA -out mykey.pem -outform PEM

    - name: Build the app
      run: |
        ~/connectiq-sdk/bin/monkeyc \
          -o bin/HelloWorld.prg \
          -m manifest.xml \
          -y mykey.pem \
          source/HelloWorldApp.mc

    - name: Upload the built .prg file
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-app
        path: bin/HelloWorld.prg
